// This file was generated by dtk-settings-tools version 0.1.2 

#include <DSettings>

void GenerateSettingTranslate()
{
    auto base_image_dir_select_work_dirName = QObject::tr("select dir");
    auto base_rotate_settings_enable_rotateText = QObject::tr("Enable rotate");
    auto base_rotate_settings_rotate_modeName = QObject::tr("  ");
    auto base_rotate_settings_rotate_modeText0 = QObject::tr("Positive sequence");
    auto base_rotate_settings_rotate_modeText1 = QObject::tr("Reverse order");
    auto base_rotate_settings_rotate_modeText2 = QObject::tr("Random");
    auto base_rotate_settings_rotate_timeName = QObject::tr("Rotate time(s)");
    auto group_baseName = QObject::tr("Basic settings");
    auto group_base_image_dirName = QObject::tr("Select directory");
    auto group_base_rotate_settingsName = QObject::tr("Rotate settings");
}
